### PR TITLE
Update minimist

### PR DESCRIPTION
**Pull request by nied**
Hi! 👋 
This PR updates the version of `minimist` to fix https://github.com/advisories/GHSA-xvch-5gv4-984h.
The tests seem to pass, let me know if you need anything else!

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Note that this is not needed at all, you can just update your dependencies.

**Comment by nied** [comment]
So, just an update on why I think the change is needed: `mqtt` is a package that has a dependency on `commist` and `aws-iot-device-sdk` depends on `mqtt`, so when `aws-iot-device-sdk` is built, they ship an old version of `minimist` as `commist` specifies that version. Let me know if I missed something or if something is unclear - I'm not really seeing why you would close this?

**Comment by mcollina** [comment]
`aws-iot-device-sdk` should just update their dependencies and they will get the update anyway, that's what `^` mean.

**Comment by nied** [comment]
Allright, but why would you not want this change in your repo? I fail to see the harm in upgrading in this repo as well?

**Comment by StevenStreib** [comment]
I can definitely see the value here. Let me see if I can rephrase what @nied is asking for here.

- `aws-iot-device-sdk-js` depends on `mqtt` at `4.2.8` (strict)
- `mqtt@4.2.8` depends on `commist` at `^1.0.0` (minor and patch upgrades permitted)
- `commist` currently depends on a version of `minimist` with a published critical severity CVE fixed in `1.2.6`

The proposed change simply ensures that the latest version of `commist` specifies the *minimum safe version* to be included when this package is installed.

Please reopen this PR and re-approve it.

**Pull request closed without merging**
